# Generated by Django 4.1.5 on 2023-02-02 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoListAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 2, 6, 57, 28, 299854)),
        ),
    ]
